### ISSUE TITLE
Orphaned cache keys

### ISSUE THREAD

**Issue by mkutyba** [colinmollenhour/Cm_Cache_Backend_Redis#116]
Hello,

I have deleted some keys using "Delete Keys" dialog. But only tags was deleted and keys remain untouched. So now they are orphans and I have no idea how to delete them. The method `_collectGarbage` doesn't help, orphaned keys remain.

**Comment by colinmollenhour** [comment]
I don't know anything about this Delete Keys dialog but deleting a key should never result in a tag being deleted because when deleting specific keys the cleaning up of empty tags is left up to garbage collection. However, I recommend using the lua option to avoid things like race conditions that can result in corrupted metadata.
