### ISSUE TITLE
there is no module.xml necessary?

### ISSUE THREAD

**Issue by seansan** [colinmollenhour/Cm_Cache_Backend_Redis#119]
there is no module.xml necessary?

Sorry used to seeing a module.xml file, I dont understand how this extenstion is "auto" picked up

**Comment by colinmollenhour** [comment]
The M1 autoloader simply replaces _ with / and searches the include paths. Since this is just a class and has no models, helpers, etc. it is not necessary to be a real "module". You disable it by simply not specifying the class name in the config. Which version is preferred in the presence of multiple versions is dependent on the include path order.
